package:
  name: q2-amr
  version: {{ PLUGIN_VERSION }}

source:
  path: ../..

build:
  script-env:
    - PLUGIN_VERSION
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - ncbi-amrfinderplus
    - python {{ python }}
    - qiime2 {{ qiime2_epoch }}.*
    - q2-demux {{ qiime2_epoch }}.*
    - q2-feature-table {{ qiime2_epoch }}.*
    - q2-types {{ qiime2_epoch }}.*
    - q2templates {{ qiime2_epoch }}.*
    - q2cli {{ qiime2_epoch }}.*
    - rgi
    - tqdm

test:
  requires:
    - coverage
    - pytest-cov
  imports:
    - q2_amr
    - qiime2.plugins.amr
  commands:
    - pytest --cov q2_amr --cov-report xml:coverage.xml --pyargs q2_amr

about:
  home: https://github.com/bokulich-lab/q2-amr
  license: BSD-3-Clause
  license_family: BSD
