name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          version: "23.12.1"
      - name: Lint with pre-commit pattern
        run: |
          find . -name "*.py" | grep -E '^((?!_version).)*\.py$' | xargs black --check
        shell: bash
